all: paper

paper:  
	pdflatex dissertation
	bibtex dissertation
	pdflatex dissertation
	pdflatex dissertation
clean: 
	rm -f dissertation.aux dissertation.bbl dissertation.blg dissertation.dvi dissertation.log 
