/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *   * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package edu.ucsb.cs.eager.sa.kitty;

import edu.ucsb.cs.eager.sa.cerebro.CFGAnalyzer;
import edu.ucsb.cs.eager.sa.cerebro.Cerebro;
import edu.ucsb.cs.eager.sa.kitty.qbets.QBETSTracingPredictor;
import edu.ucsb.cs.eager.sa.kitty.qbets.SimpleQBETSPredictor;
import edu.ucsb.cs.eager.sa.kitty.simulation.SimulationBasedPredictor;
import org.apache.commons.cli.*;
import soot.SootMethod;

import java.io.*;
import java.util.*;

/**
 * Kitty analyzes trace files generated by Cerebro and makes
 * predictions regarding the timing of the function calls. It picks
 * the worst-case paths from Cerebro traces and predicts their
 * execution time. Kitty is named after Kitty Pryde, for her ability of
 * phasing through the currents of time.
 */
public class Kitty {

    public static void main(String[] args) throws IOException {
        Options options = new Options();
        options.addOption("i", "input-file", true,
                "Path to the Cerebro trace file");

        options.addOption("ccp", "cerebro-classpath", true,
                "Cerebro classpath");
        options.addOption("c", "class", true,
                "Class to be used as the starting point");
        options.addOption("dnc", "disable-nec-classes", false,
                "Disable loading of necessary classes");
        options.addOption("wp", "whole-program", false,
                "Enable whole program mode");
        options.addOption("m", "methods", true,
                "Methods that should be analyzed");

        options.addOption("b", "benchmark-dir", true,
                "Path to the directory containing seed benchmark results");
        options.addOption("sn", "simulations", true,
                "Number of times to simulate each path (default 100)");

        options.addOption("s", "benchmark-svc", true,
                "URL of the benchmark data service");
        options.addOption("q", "quantile", true,
                "Execution time quantile that should be predicted");
        options.addOption("cn", "confidence", true,
                "Upper confidence of the predicted execution time quantile");
        options.addOption("a", "aggregate-ts", false,
                "Aggregate multiple time series into a single time series");
        options.addOption("sp", "simple", false,
                "Use the simple QBETS predictor");

        CommandLine cmd;
        try {
            CommandLineParser parser = new BasicParser();
            cmd = parser.parse( options, args);
        } catch (ParseException e) {
            System.err.println("Error: " + e.getMessage() + "\n");
            HelpFormatter formatter = new HelpFormatter();
            formatter.printHelp("Kitty", options);
            return;
        }

        PredictionConfig config = new PredictionConfig();
        config.setTraceFile(cmd.getOptionValue("i"));
        config.setCerebroClasspath(cmd.getOptionValue("ccp"));
        config.setClazz(cmd.getOptionValue("c"));
        config.setLoadNecessaryClasses(!cmd.hasOption("dnc"));
        config.setWholeProgramMode(cmd.hasOption("wp"));

        String methods = cmd.getOptionValue("m");
        if (methods != null) {
            config.setMethods(methods.split(","));
        }

        config.setBenchmarkDataDir(cmd.getOptionValue("b"));
        String sn = cmd.getOptionValue("sn");
        if (sn != null) {
            config.setSimulations(Integer.parseInt(sn));
        }
        config.setBenchmarkDataSvc(cmd.getOptionValue("s"));
        String q = cmd.getOptionValue("q");
        if (q != null) {
            config.setQuantile(Double.parseDouble(q));
        }
        String c = cmd.getOptionValue("cn");
        if (c != null) {
            config.setConfidence(Double.parseDouble(c));
        }
        config.setAggregateTimeSeries(cmd.hasOption("a"));
        config.setSimplePredictor(cmd.hasOption("sp"));

        try {
            config.validate();
        } catch (Exception e) {
            System.err.println(e.getMessage());
            return;
        }

        Kitty k = new Kitty();
        k.run(config);
    }

    public void run(PredictionConfig config) throws IOException {
        Collection<MethodInfo> methods;
        if (config.getTraceFile() != null) {
            TraceLogParser parser = new TraceLogParser();
            parser.parseFile(config.getTraceFile());
            methods = parser.getMethods();
        } else {
            methods = getMethodsFromCerebro(config);
        }

        if (config.getBenchmarkDataDir() != null) {
            SimulationBasedPredictor.predict(config, methods);
        } else if (config.getBenchmarkDataSvc() != null) {
            if (config.isSimplePredictor()) {
                SimpleQBETSPredictor.predict(config, methods);
            } else {
                QBETSTracingPredictor.predict(config, methods);
            }
        } else {
            throw new IllegalArgumentException();
        }
    }

    private Collection<MethodInfo> getMethodsFromCerebro(PredictionConfig config) {
        Cerebro cerebro = new Cerebro(config.getCerebroClasspath(), config.getClazz());
        cerebro.setLoadNecessaryClasses(config.isLoadNecessaryClasses());
        cerebro.setWholeProgramMode(config.isWholeProgramMode());
        try {
            Map<SootMethod,CFGAnalyzer> results = cerebro.analyze();
            Set<MethodInfo> methods = new TreeSet<MethodInfo>(new MethodInfo.MethodInfoComparator());
            for (Map.Entry<SootMethod,CFGAnalyzer> entry : results.entrySet()) {
                MethodInfo mi = new MethodInfo(entry.getKey().getName());
                for (List<SootMethod> path : entry.getValue().getPaths()) {
                    Path callPath = new Path();
                    for (SootMethod sm : path) {
                        callPath.add(new APICall(sm.getDeclaringClass().getName() + "#" +
                                sm.getName() + "()"));
                    }
                    mi.addPath(callPath);
                }
                methods.add(mi);
            }
            return methods;
        } finally {
            cerebro.cleanup();
        }
    }

}
