/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *   * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package edu.ucsb.cs.eager.sa.kitty;

import edu.ucsb.cs.eager.sa.kitty.qbets.QBETSBasedPredictor;
import edu.ucsb.cs.eager.sa.kitty.simulation.SimulationBasedPredictor;
import org.apache.commons.cli.*;

import java.io.*;
import java.util.*;

/**
 * Kitty analyzes trace files generated by Cerebro and makes
 * predictions regarding the timing of the function calls. It picks
 * the worst-case paths from Cerebro traces and predicts their
 * execution time. Kitty is named after Kitty Pryde, for her ability of
 * phasing through the currents of time.
 */
public class Kitty {

    public static void main(String[] args) throws IOException {
        Options options = new Options();
        options.addOption("i", "input-file", true,
                "Path to the Cerebro trace file");
        options.addOption("b", "benchmark-dir", true,
                "Path to the directory containing seed benchmark results");
        options.addOption("sn", "simulations", true,
                "Number of times to simulate each path (default 100)");
        options.addOption("s", "benchmark-svc", true,
                "URL of the benchmark data service");
        options.addOption("q", "quantile", true,
                "Execution time quantile that should be predicted");
        options.addOption("c", "confidence", true,
                "Upper confidence of the predicted execution time quantile");
        options.addOption("a", "aggregate-ts", false,
                "Aggregate multiple time series into a single time series");

        CommandLine cmd;
        try {
            CommandLineParser parser = new BasicParser();
            cmd = parser.parse( options, args);
        } catch (ParseException e) {
            System.err.println("Error: " + e.getMessage() + "\n");
            HelpFormatter formatter = new HelpFormatter();
            formatter.printHelp("Kitty", options);
            return;
        }

        PredictionConfig config = new PredictionConfig();
        config.setTraceFile(cmd.getOptionValue("i"));
        config.setBenchmarkDataDir(cmd.getOptionValue("b"));
        String sn = cmd.getOptionValue("sn");
        if (sn != null) {
            config.setSimulations(Integer.parseInt(sn));
        }
        config.setBenchmarkDataSvc(cmd.getOptionValue("s"));
        String q = cmd.getOptionValue("q");
        if (q != null) {
            config.setQuantile(Double.parseDouble(q));
        }
        String c = cmd.getOptionValue("c");
        if (c != null) {
            config.setConfidence(Double.parseDouble(c));
        }
        config.setAggregateTimeSeries(cmd.hasOption("a"));

        try {
            config.validate();
        } catch (Exception e) {
            System.err.println(e.getMessage());
            return;
        }

        Kitty k = new Kitty();
        k.run(config);
    }

    public void run(PredictionConfig config) throws IOException {
        List<MethodInfo> methods = getMethods(config);
        if (config.getBenchmarkDataDir() != null) {
            SimulationBasedPredictor.predict(config, methods);
        } else if (config.getBenchmarkDataSvc() != null) {
            QBETSBasedPredictor.predict(config, methods);
        } else {
            throw new IllegalArgumentException();
        }
    }

    private List<MethodInfo> getMethods(PredictionConfig config) throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader(config.getTraceFile()));
        TraceLogParser parser = new TraceLogParser();
        String line;
        try {
            while ((line = reader.readLine()) != null) {
                parser.parse(line);
            }
        } finally {
            reader.close();
        }
        return parser.getMethods();
    }

}
