package edu.ucsb.cs.roots.data;

public abstract class DataStore {

    /**
     * Retrieve the access log entries generated by the specified application during the
     * specified time interval.
     *
     * @param application Name of the application
     * @param start Start time of the interval (inclusive)
     * @param end End time of the interval (exclusive)
     * @return An array of AccessLogEntry objects
     */
    public abstract AccessLogEntry[] getAccessLogEntries(String application, long start, long end);

}
