package edu.ucsb.cs.roots.data;

import java.util.List;

public abstract class DataStore {

    /**
     * Retrieve the access log entries generated by the specified application during the
     * specified time interval.
     *
     * @param application Name of the application
     * @param start Start time of the interval (inclusive)
     * @param end End time of the interval (exclusive)
     * @return A list of AccessLogEntry objects
     */
    public abstract List<AccessLogEntry> getAccessLogEntries(String application, long start, long end);

}
